version: "3"
services:
  ratchat:
    image: ratchat
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "80:5000"
  redis:
    image: redis
    ports:
      - "6379:6739"
    volumes:
      - ./redis_data:/data
